name: Pruebas merge
on: push
jobs:
  j1:
    name: Job j1
    runs-on: ubuntu-latest
    steps:
    - name: checkout de repositorio
      uses: actions/checkout@v2
    - name: respuesta de job
      env: 
        MENSAJE: Prueba de mensaje
      run: echo "::set-output name=respuesta::${MENSAJE}"

